<a href="https://colab.research.google.com/github/zuynali/Pytorch/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.11.0+cpu


In [2]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [8]:
matrix.ndim

2

In [9]:
tensor=torch.tensor([[[1,2,3],[3,4,5],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

In [13]:
tensor=torch.tensor([[[1,2,3],[3,4,5],[7,8,9]], [[1,2,3],[3,4,5],[7,8,9]],[[1,2,3],[3,4,5],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]],

        [[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]],

        [[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [14]:
tensor.shape

torch.Size([3, 3, 3])

In [15]:
tensor[0][1]

tensor([3, 4, 5])

###Random tensors

In [20]:
rnd_t = torch.rand(3,4)
rnd_t

tensor([[0.0464, 0.3319, 0.7861, 0.5046],
        [0.8052, 0.2383, 0.7207, 0.0189],
        [0.3518, 0.8669, 0.5754, 0.5099]])

In [21]:
rnd_t.ndim

2

In [23]:
rand_image=torch.rand(224,224,3)
rand_image

tensor([[[0.0933, 0.3268, 0.1788],
         [0.6078, 0.6350, 0.1683],
         [0.9556, 0.7394, 0.9112],
         ...,
         [0.1348, 0.8988, 0.1390],
         [0.0259, 0.9684, 0.0626],
         [0.9367, 0.0402, 0.7824]],

        [[0.4788, 0.3501, 0.4561],
         [0.5830, 0.7148, 0.6020],
         [0.9584, 0.6065, 0.3203],
         ...,
         [0.0455, 0.7270, 0.5157],
         [0.1928, 0.8187, 0.6884],
         [0.7283, 0.8427, 0.1681]],

        [[0.1439, 0.4241, 0.2709],
         [0.3397, 0.2818, 0.4574],
         [0.5252, 0.9668, 0.0842],
         ...,
         [0.7464, 0.6755, 0.4801],
         [0.4337, 0.9283, 0.4277],
         [0.2264, 0.8978, 0.6840]],

        ...,

        [[0.3706, 0.0962, 0.3622],
         [0.2478, 0.3084, 0.7140],
         [0.8678, 0.3730, 0.0309],
         ...,
         [0.8157, 0.8441, 0.3365],
         [0.7855, 0.1151, 0.3949],
         [0.7048, 0.8790, 0.1850]],

        [[0.0291, 0.3850, 0.1487],
         [0.3642, 0.0549, 0.0132],
         [0.

In [24]:
rand_image.ndim

3

In [25]:
rand_image.shape

torch.Size([224, 224, 3])

In [27]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])